/* eslint-disable @typescript-eslint/strict-boolean-expressions */

import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Button } from "@mui/material";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";

export default function Home(): JSX.Element {
  const router = useRouter();
  function randomRoomString(): string {
    return Math.random().toString(36).substring(2, 7);
  }
  const [randomRoom, setRandomRoom] = useState<string>("");
  const [room, setRoom] = useState<string>("");

  useEffect(() => {
    setRoom(randomRoomString());
    setRandomRoom(randomRoomString());
  }, []);
  return (
    <>
      <Head>
        <title>Online chatrooms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Button
          variant="contained"
          onClick={() => {
            void router.push(`/room/${randomRoom}`);
          }}
        >
          Join a random room {"("}
          {randomRoom}
          {")"}
        </Button>
        <input
          value={room}
          onChange={(e) => {
            setRoom(e.target.value);
          }}
        ></input>
        <Button
          variant="contained"
          onClick={() => {
            void router.push(`/room/${room}`);
          }}
        >
          Join room : {room}
        </Button>
      </main>
    </>
  );
}
