/* eslint-disable @typescript-eslint/strict-boolean-expressions */
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect } from "react";
import { io, type Socket } from "socket.io-client";
import type {
  ServerToClientEvents,
  ClientToServerEvents,
} from "@/types/socketCustomTypes";
import { Button } from "@mui/material";

let socket: Socket<ServerToClientEvents, ClientToServerEvents> | null = null;

export default function Home(): JSX.Element {
  useEffect(() => {
    if (!socket) {
      void fetch("/api/socket");
      socket = io();

      socket.on("connect", () => {
        console.log("connected");
      });

      socket.on("hello", (msg: string) => {
        console.log("hello", msg);
      });

      socket.on("userServerConnection", () => {
        console.log("a user connected (client)");
      });

      socket.on("userServerDisconnection", (socketid: string) => {
        console.log(socketid);
      });
    }

    return () => {
      if (socket) {
        socket.disconnect();
        socket = null;
      }
    };
  }, []);
  return (
    <>
      <Head>
        <title>Online chatrooms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Button
          variant="contained"
          onClick={() => socket?.emit("hello", "kitty")}
        >
          Send Hello {'"'}Kitty{'"'}
        </Button>
        <Button variant="contained">Create a chatroom</Button>
        <Button variant="contained">Join a chatroom</Button>
      </main>
    </>
  );
}
